### PR TITLE
Add timeout to amqp_login and amqp_login_with_properties

### PR DESCRIPTION
**Pull request by Haster2004**
subj

[Review on Reviewable](https://reviewable.io/reviews/alanxz/rabbitmq-c/302)

### CODE REVIEW

**Comment by alanxz** [comment]
Sorry for the delay, I'll try and take a look at this in the next couple days.

**Comment by alanxz** [comment]
This Fixes #302

**Comment by alanxz** [comment]
Instead of merging upstream commits, use `git rebase` to rebase your commits on top of the latest changes to rabbitmq-c . Merge commits make it more difficult to understand whats going on.

Couple general issues here:
1. Currently when `amqp_login_noblock()` returns a timeout error, the connection can be left in a connected, but half-logged in state. The semantics of what happens need to be clearly defined and enforced. I suspect what we want to do here is when we timeout in the login, the connection should be torn down completely.
2. The `timeout` parameter doesn't quite work as advertised. The same timeout parameter is used for each RPC round-trip, which means over a slow connection the actual timeout is more like `N * timeout`, where N is the number of round-trips. You probably want to use `[amqp_time_from_now()](https://github.com/alanxz/rabbitmq-c/blob/48311c88684724a23740988828e0052d39389138/librabbitmq/amqp_time.h#L75) and friends to make sure you actually have a single timeout for the whole call.


---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[librabbitmq/amqp.h, line 1647 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wH3Om-6zS5-ICs64J)** ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L1647)):</sup>
amqp_simple_wait_method() is something that should likely not have been made public. I'd prefer to keep this as private for the time being.


---

<sup>**[librabbitmq/amqp.h, line 1763 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wI81vZCqSIekQKNfC)** ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L1763)):</sup>
This is also something that should probably not be a public function.


---

<sup>**[librabbitmq/amqp.h, line 1950 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wIGKFHGxj0EtkHnvd)** ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L1950)):</sup>
I'm not wild about adding 2 new functions, lets limit it to `amqp_login_with_properties_noblock()` (Get rid of this one).


---

<sup>**[librabbitmq/amqp.h, line 2067 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wM49MAibUHlMaPOcS)** ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L2067)):</sup>
`\since v0.8.0`

v0.7.1 has already shipped.


---

<sup>**[librabbitmq/amqp.h, line 2072 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wME0X_7-IfctzxxJd)** ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L2072)):</sup>
Wrap at 80 characters, here and throughout.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302)

**Comment by Haster2004** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[librabbitmq/amqp.h, line 1647 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wH3Om-6zS5-ICs64J:-K7uIJ0EFHYLM4n8H4oq:768356014) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L1647)):*
I made amqp_simple_wait_method_noblock public  similarly to amqp_simple_wait_method, that is public.
But if you thinks that _noblock method has to be private ok =)

---

*[librabbitmq/amqp.h, line 1950 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wIGKFHGxj0EtkHnvd:-K7uJIqEJcNBzpg12_l9:-1121742516) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L1950)):*
Won't it brake backward compatibility? Because amqp_login_noblock is you function. I added here only amqp_login_noblock function.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302)*

**Comment by Haster2004** [comment]
sorry for new merge commit: I am junior with github

**Comment by alanxz** [comment]
You'll need to address the blocking nature of sending the methods to the broker `amqp_send_method`, within `amqp_login_inner`

Do not add _noblock variants of the functions declared in `amqp_framing.h`. The problem with adding a a timeout to these functions is that when the function returns a timeout, its possible given a short enough timeout that a partial response from the broker may have been received, at this point doing another RPC on the same channel will result in the connection being incorrectly closed. Making it a requirement that users of the API specify a 'long-enough' timeout is not a reasonable workaround as, its not clear how to define 'long-enough', and would make the API difficult to use correctly. I'm willing to explore how this might be done in a way that is easy to use, but not in this PR.

---

Review status: 0 of 4 files reviewed at latest revision, 12 unresolved discussions.

---

*[librabbitmq/amqp.h, line 1647 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wH3Om-6zS5-ICs64J:-K8KOFV1j8Wis538Lpqn:1271673707) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L1647)):*
For most users, they will not use this API function directly. Please remove from the public API.

---

*[librabbitmq/amqp.h, line 1763 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wI81vZCqSIekQKNfC:-K8NCBuRmzrx50hhoxKL:1271673707) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L1763)):*
For most users, they will not use this API function directly. Please remove from the public API.

---

*[librabbitmq/amqp.h, line 1950 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wIGKFHGxj0EtkHnvd:-K8NCi-61uIfW94vbYnv:-185624904) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L1950)):*
You're not replacing amqp_login, so not adding this function will not break backward compatibility.

---

*[librabbitmq/amqp.h, line 1813 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NCet9sEajaMQfEf0c:-K8NCet9sEajaMQfEf0d:1271673707) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp.h#L1813)):*
For most users, they will not use this API function directly. Please remove from the public API.

---

*[librabbitmq/amqp_framing.c, line 1963 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8ND8TcXbNxnk6u4Oqe:-K8ND8TcXbNxnk6u4Oqf:-714954780) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_framing.c#L1963)):*
amqp_framing.c and amqp_framing.h are generated code. You need to modify the codegen.py file, then specify -DREGENERATE_AMQP_FRAMING=ON to CMake to generate new versions of these files.

---

*[librabbitmq/amqp_socket.c, line 1311 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NIcEi2zhP6e7Z0Ttk:-K8NIcEi2zhP6e7Z0Ttl:754404295) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_socket.c#L1311)):*
leave as `res != AMQP_STATUS_OK`

---

*[librabbitmq/amqp_socket.c, line 1312 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NRp4ehTzoDdjVyOpD:-K8NRp4ehTzoDdjVyOpE:-356798285) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_socket.c#L1312)):*
Currently when amqp_login errors out, it doesn't close the socket for you. Don't close the socket on timeout. (here and below).

---

*[librabbitmq/amqp_socket.c, line 1399 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NReVsOAVHAID15Iax:-K8NReVsOAVHAID15Iay:-1611718640) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_socket.c#L1399)):*
What about sends? Its possible for this to block.

---

*[librabbitmq/amqp_socket.c, line 1519 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NNvASUKVKYfdwiQhg:-K8NNvASUKVKYfdwiQhh:823488713) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_socket.c#L1519)):*
Don't add an extra later here, just change `amqp_login_inner` and anything that references it so that it accepts a timeout argument, since amqp_login_inner isn't public, its possible to do this.

---

*[librabbitmq/amqp_socket.c, line 1612 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NNn37FhnlFGlRKJw2:-K8NNn37FhnlFGlRKJw3:1535210086) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_socket.c#L1612)):*
Wrap at 80 characters please.  Here and throughout.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-:-K8NOU7L61RTtNzkXiBQ:1342910318)*

**Comment by Haster2004** [comment]
*[librabbitmq/amqp_framing.c, line 1963 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8ND8TcXbNxnk6u4Oqe:-K8OHRrwtYq9BklxbP_E:169271051) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_framing.c#L1963)):*
As I understand now I don't have to do it because you said delete all _noblock functions from amqp_framing.h/c files. Am I right?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302)*

**Comment by Haster2004** [comment]
*[librabbitmq/amqp.h, line 1647 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wH3Om-6zS5-ICs64J:-K8OI4iGE8pIsZ90VDC1:1974175124) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L1647)):*
Do I have to just delete AMQP_PUBLIC_FUNCTION from prototype or I have to put this method to another source file?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302)*

**Comment by Haster2004** [comment]
Yep, I'm agree that there is some problem.
In my case I just close connection after such errors and open new one.
But it is not common solution ).
Ok, I will revert amqp_framing.h (c) files

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-:-K8OIbr8jVhu266ohQHk:520465391)*

**Comment by Haster2004** [comment]
Review status: 0 of 4 files reviewed at latest revision, 12 unresolved discussions.

---

*[librabbitmq/amqp.h, line 2067 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wM49MAibUHlMaPOcS:-K8JVoICTsnGCB5aZ5Kb:-499146009) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L2067)):*
Done.

---

*[librabbitmq/amqp.h, line 2072 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wME0X_7-IfctzxxJd:-K8JVp83jYMQ9MyKGJPX:-499146009) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L2072)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302)*

**Comment by Haster2004** [comment]
Review status: 0 of 4 files reviewed at latest revision, 12 unresolved discussions.

---

*[librabbitmq/amqp_socket.c, line 1311 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NIcEi2zhP6e7Z0Ttk:-K8OJICvwJBcqRnQeG2v:-499146009) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_socket.c#L1311)):*
Done.

---

*[librabbitmq/amqp_socket.c, line 1312 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NRp4ehTzoDdjVyOpD:-K8OJMj3bytRtrxiMAxB:-499146009) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_socket.c#L1312)):*
Done.

---

*[librabbitmq/amqp_socket.c, line 1519 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NNvASUKVKYfdwiQhg:-K8OJKz77TE6tHqLSR8f:-499146009) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_socket.c#L1519)):*
Done.

---

*[librabbitmq/amqp_socket.c, line 1612 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NNn37FhnlFGlRKJw2:-K8OJKN4pXW8d-Qza8PG:-499146009) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_socket.c#L1612)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302)*

**Comment by Haster2004** [comment]
*[librabbitmq/amqp_socket.c, line 1399 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NReVsOAVHAID15Iax:-K8OKtTp7Ds_8o2oNCf-:1585320550) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_socket.c#L1399)):*
Is it possible?
This method use amqp_try_recv which use immediate timeout on recv.
Or do you mean that it can block on sending?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302)*

**Comment by Haster2004** [comment]
Review status: 0 of 4 files reviewed at latest revision, 12 unresolved discussions.

---

*[librabbitmq/amqp.h, line 1950 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wIGKFHGxj0EtkHnvd:-K8OM4ovoRzzIBHEiq9q:-499146009) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L1950)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302)*

**Comment by alanxz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[librabbitmq/amqp.h, line 1647 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wH3Om-6zS5-ICs64J:-K8Rd1j05JYBGvANngrb:-330684227) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L1647)):*
amqp.h should only have public functions in it. If you need to have a declaration, so that the function can be used from different translation units, put it in the .h file associated with the .c file in which its defined.

---

*[librabbitmq/amqp_framing.c, line 1963 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8ND8TcXbNxnk6u4Oqe:-K8PcYJaUj_C4vuqlGVW:-496775834) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_framing.c#L1963)):*
That is correct.

---

*[librabbitmq/amqp_socket.c, line 1399 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NReVsOAVHAID15Iax:-K8wk9tc4w4XS4ECEHrB:-1712280905) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_socket.c#L1399)):*
amqp_send_method could block.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302)*

**Comment by Haster2004** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[librabbitmq/amqp.h, line 1647 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wH3Om-6zS5-ICs64J:-K8xLGsuDxYIqBitQ-bh:-499146009) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L1647)):*
Done.

---

*[librabbitmq/amqp.h, line 1763 \[r2\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K0wI81vZCqSIekQKNfC:-K8xLI5B0mhG7qY0pVbM:-499146009) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/55fe73f5a2954d12857538e3526d0eb65faf6abf/librabbitmq/amqp.h#L1763)):*
Done.

---

*[librabbitmq/amqp.h, line 1813 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NCet9sEajaMQfEf0c:-K8xLJIW2Y5US-geQEux:-499146009) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp.h#L1813)):*
Done.

---

*[librabbitmq/amqp_framing.c, line 1963 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8ND8TcXbNxnk6u4Oqe:-K8xLLHGBkuTrQucJOzU:-499146009) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_framing.c#L1963)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302)*

**Comment by alanxz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[librabbitmq/amqp.h, line 1813 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NCet9sEajaMQfEf0c:-K9VmfvxdW-k_A6No12L:-1784183778) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp.h#L1813)):*
nit: an extra newline snuck in here. Please remove.

---

*[librabbitmq/amqp.h, line 1677 \[r6\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K9VmZDE0_lZpP9foPKO:-K9VmZDF8g2EefDAsR97:-21992268) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/2519759c312578ef734c26e8546b3343fcc774e3/librabbitmq/amqp.h#L1677)):*
nit: remove this line

---

*[librabbitmq/amqp_socket.c, line 1399 \[r4\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302#-K8NReVsOAVHAID15Iax:-KA3OgPO_O5_OKYEYerF:1495615461) ([raw file](https://github.com/alanxz/rabbitmq-c/blob/6e0165a39e9643d88bae3adbff16a0abb32d3b9d/librabbitmq/amqp_socket.c#L1399)):*
This still needs work.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/302)*

**Comment by Haster2004** [comment]
@alanxz, hi!
Is it good if I start new Pull Request where I transfer code from this PR?
The problem is that I have created this PR from master branch and now I have to
make merge instead of rebase to sync with upstream.

**Comment by alanxz** [comment]
Yes, feel free to open a new PR if you think it'll make it easier for you.

**Comment by alanxz** [comment]
Would have fixed #300.

Closing as work is being done in #383

**Pull request closed without merging**
