### PR TITLE
[Fuzzing] oss-fuzz ideal

### PR DESCRIPTION
**Pull request by 0x34d**
* add [cifuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration) for oss-fuzz ideal.

### CODE REVIEW

**Comment by 0x34d** [comment]
Update:  Working on `fuzz_server.c` there are some problem in the test.

**Comment by alanxz** [comment]
The fuzz_server fuzz-test seems to fail when trying to create a network socket. My guess is that the frequency of creating and destroying sockets results in the system running the test quickly running out of sockets, which causes the test to start failing.

So I suspect additional work is required to make fuzz_server work. If you want to pursue fixing fuzz_server, would you mind opening a separate PR for fuzz_server.

If you'd like to land this PR, lets limit the Action to running just the fuzzers known to work consistently (so exclude fuzz_server). 

I've added the two actions required for the oss-fuzz action to the allowlist, so it should be able to run now.

**Comment by 0x34d** [comment]
> The fuzz_server fuzz-test seems to fail when trying to create a network socket. My guess is that the frequency of creating and destroying sockets results in the system running the test quickly running out of sockets, which causes the test to start failing.

I don't think so.

> So I suspect additional work is required to make fuzz_server work. If you want to pursue fixing fuzz_server, would you mind opening a separate PR for fuzz_server.

Yes, but the other methods are too complex and require thread Mutex.


> If you'd like to land this PR, lets limit the Action to running just the fuzzers known to work consistently (so exclude fuzz_server).

I did't get it this will works fine, so way?

> I've added the two actions required for the oss-fuzz action to the allowlist, so it should be able to run now.

alright.

**Comment by 0x34d** [comment]
After this PR https://github.com/google/oss-fuzz/pull/10657 is merged, i think all CIfuzz will work fine.

**Comment by 0x34d** [comment]
Trigger CI

**Comment by 0x34d** [comment]
> The fuzz_server fuzz-test seems to fail when trying to create a network socket. My guess is that the frequency of creating and destroying sockets results in the system running the test quickly running out of sockets, which causes the test to start failing.

It was happening because there was no data to send from server to client under test.
 
> So I suspect additional work is required to make fuzz_server work. If you want to pursue fixing fuzz_server, would you mind opening a separate PR for fuzz_server.

Alrday done on https://github.com/alanxz/rabbitmq-c/pull/786


> If you'd like to land this PR, lets limit the Action to running just the fuzzers known to work consistently (so exclude fuzz_server).

I don't think so this is possible, because there is no way to exclude any particular fuzzer.


> I've added the two actions required for the oss-fuzz action to the allowlist, so it should be able to run now.

Thanks.


Can we talk on Merge now?

**Comment by alanxz** [comment]
> It was happening because there was no data to send from server to client under test.

The issue I have observed with fuzz_server under ClusterFuzz is that `amqp_socket_open` fails, and errno is set to 101 or "Network is unreachable" (see: https://crbug.com/oss-fuzz/56170, and the associated test detail here: https://oss-fuzz.com/testcase-detail/4840737083883520). I have not been able to resolve whatever issue is happening here. We can proceed with this PR as long as this CI-Fuzz works reliably (meaning it consistently runs without this sort of error).

> Can we talk on Merge now?

Please remove the last 2 commits from this PR (so that only cb37d1d remains), rebase against current master, and push (likely a force-push is required), then I can merge this in.

**Comment by 0x34d** [comment]
> > It was happening because there was no data to send from server to client under test.
> 
> The issue I have observed with fuzz_server under ClusterFuzz is that `amqp_socket_open` fails, and errno is set to 101 or "Network is unreachable" (see: https://crbug.com/oss-fuzz/56170, and the associated test detail here: https://oss-fuzz.com/testcase-detail/4840737083883520). I have not been able to resolve whatever issue is happening here. We can proceed with this PR as long as this CI-Fuzz works reliably (meaning it consistently runs without this sort of error).

There are two threads; the detached thread doesn't have any data to send in `send`, so it exits as `Unexpected-exit`.
And I'm open to my unknowns and your knowns.

CIFuzz is working reliably; you can check the [Run Fuzzers (Address)](https://github.com/alanxz/rabbitmq-c/actions/runs/5503887126/jobs/10029526597).

 

> > Can we talk on Merge now?
> 
> Please remove the last 2 commits from this PR (so that only [cb37d1d](https://github.com/alanxz/rabbitmq-c/commit/cb37d1d76b9776bf61fc2bc5f8678737155f38fc) remains), rebase against current master, and push (likely a force-push is required), then I can merge this in.

Alright, Done.

**Pull request merged**
