### PR TITLE
Add methods to get frame_max and heartbeat of the connection, closes #243

### LINKED ISSUE #243: Function to get frame_max and heartbeat from connection_state
There are already `int amqp_get_channel_max(amqp_connection_state_t state)` to get `channel_max`, 
and it will be a good idea to defer `frame_max` and `heartbeat` from user-space code?

I need to have such public functions to get actual `frame_max` and `hearbeat` in [php-amqp](https://github.com/pdezwart/php-amqp).

Can you specify any estimates when you'll be rolling next release and will you include such features (very trivial one) in it if I provide PR?

### PR DESCRIPTION
**Pull request by pinepain**

### CODE REVIEW

**Comment by pinepain** [comment]
As discussed in https://github.com/alanxz/rabbitmq-c/issues/243. Can you check functions description whether they fit library standards?

**Comment by alanxz** [comment]
FYI: Github doesn't send me any notification to me when PRs are updated. Please ping this ticket when you're ready to have this re-reviewed.

**Comment by pinepain** [comment]
Sorry, I just was in a hurry so I just "hack and slash". Now I'm back to normal life. BTW, when changes reviewed in commit rather then in "Files changed" tab, commit messages are not attached to conversation and live with their own life, so it is not obvious that someone made any comment until you get into that commit (emails are also move behind usual ghithub mailing list filter while they are directed only to commiter rather then to all issue/pr watchers).

**Comment by alanxz** [comment]
Ugh: UX failure. Thanks for the tip though, I'll keep that in mind when I do future reviews.

**Pull request merged**
