### PR TITLE
Flexelint'ed

### PR DESCRIPTION
**Pull request by isj4**
Preliminary patch set of warnings found with Flexelint. Most of it is just simple cleanup, clarifications and simplifications. Overall, rabbitmq-c was already in a decent state before this but I have a hunch that most people just compiled it with compiler warnings turned down.
The change of char* -> const char * in amqp_connection_info could potentially break compilation of badly written programs.

There are some other potential API changes, but I'll PM them.

[Review on Reviewable](https://reviewable.io/reviews/alanxz/rabbitmq-c/314)

### CODE REVIEW

**Comment by alanxz** [comment]
First: thanks for taking the time to do this, I like most of what's being addressed here.

A couple general comments:

1. These changes break the build on Linux (and maybe Mac OS X), if you don't have access to a linux system, use the travis-ci build attached to this repository to help you debug (they should re-run on those systems each time you push to this branch). I won't spend a lot of time reviewing this set of changes if they're not correctly building on all platforms
2. Please squash all the changes to the flexilint config file into one commit.
3. Please re-word the commit messages so that they follow [git formatting](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html):
```
Capitalized, short (50 chars or less) summary

More detailed explanatory text, if necessary.  Wrap it to about 72
characters or so.  In some contexts, the first line is treated as the
subject of an email and the rest of the text as the body.  The blank
line separating the summary from the body is critical (unless you omit
the body entirely); tools like rebase can get confused if you run the
two together.

Write your commit message in the imperative: "Fix bug" and not "Fixed bug"
or "Fixes bug."  This convention matches up with commit messages generated
by commands like git merge and git revert.

Further paragraphs come after blank lines.

- Bullet points are okay, too

- Typically a hyphen or asterisk is used for the bullet, followed by a
  single space, with blank lines in between, but conventions vary here

- Use a hanging indent
```
4. Code format: please follow the format of the code around it. The big ones are you need more space between things (I'll point out a few examples below). 


---

Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

<sup>**[librabbitmq/amqp_connection.c, line 147 \[r1\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/314#-K0wCpcymossgOxoqiL-)** ([raw file](https://github.com/alanxz/rabbitmq-c/blob/bd84e9faa615a46670c14e53848182979e07bb52/librabbitmq/amqp_connection.c#L147)):</sup>
Not enough space between items here, it should look like:

```c
if (channel_max < 0 || channel_max > UINT16_MAX) {
```


---

<sup>**[librabbitmq/amqp_connection.c, line 151 \[r1\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/314#-K0wEFQslZ12eCMVMGVI)** ([raw file](https://github.com/alanxz/rabbitmq-c/blob/bd84e9faa615a46670c14e53848182979e07bb52/librabbitmq/amqp_connection.c#L151)):</sup>
Likewise here:

```c
if (frame_max < 0) {
```

Do this for all changes.


---

<sup>**[librabbitmq/amqp_connection.c, line 304 \[r1\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/314#-K0wEMgCadIcsJ_QuATL)** ([raw file](https://github.com/alanxz/rabbitmq-c/blob/bd84e9faa615a46670c14e53848182979e07bb52/librabbitmq/amqp_connection.c#L304)):</sup>
Add a space after the start of the comment and before the end of the comment:

```c
/* FALLTHROUGH */
```

Here and throughout


---

<sup>**[librabbitmq/amqp_framing.c, line 1889 \[r1\]](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/314#-K0wEmwwrx11AiPQaXge)** ([raw file](https://github.com/alanxz/rabbitmq-c/blob/48311c88684724a23740988828e0052d39389138/librabbitmq/amqp_framing.c#L1889)):</sup>
This file is generated by [codegen.py](https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/codegen.py).  You must modify that script, then re-run it to make changes to this file.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/314)

**Comment by isj4** [comment]
A plain "cd build && cmake --build ." doesn't build tools/, so I didn't catch that error. I'll fix tools/

it wasn't clear to me that codegen.py wasn't just a leftover from older version as its output is checked into the repository. I'll see what I can do.

> Please squash all the changes to the flexilint config file into one commit.
My git kung-fu is too weak for such tasks. 

But I'll see what I can do about the other commit messages and the code minor formatting issues.

**Comment by alanxz** [comment]
Tools doesn't build on Win32, because it requires libpopt, which I haven't been able to find for Win32.

**Comment by alanxz** [comment]
I've cherry-picked the following commits:
- 24433b5 Use logical-or instead of bitwise-or in preprocessor conditional -> 914c390
- 438143f Removed superfluous and suspicious cast in amqp_simple_rpc() call. 'r... -> 55358b4
- 230b043 Removed unused local macro RPC_REPLY -> ba0bd1e
- 2716c06, b548450 Removed unused `include <assert.h>` -> 197a5d3
- d7b5ff5 Don't initialize local variable last_error because it is immediately … -> 882cf80


---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alanxz/rabbitmq-c/314)

**Comment by alanxz** [comment]
I've taken all the changes I'm going to take from this, they appeared in the v0.8.0 release.

Thanks for the contributions!

**Comment by isj4** [comment]
Thanks. Sorry for not updating the changes - I have had my hands full with other things.

**Pull request closed without merging**
