### PR TITLE
use -std=gnu99 instead of -std-gnu90

### LINKED ISSUE #291: compiling with clang creates a lot of warnings w.r.t. long long
On OS X, I always compile the library using clang. This generates a lot of warnings due to the use of long long, which apparently isn't part of the c90 standard, but is silently accepted by gcc -std=gnu90

Example:

````
In file included from librabbitmq/amqp_openssl.c:33:
In file included from ./librabbitmq/amqp_socket.h:35:
./librabbitmq/amqp_private.h:339:37: warning: 'long long' is an extension when C99 mode is not
      enabled [-Wlong-long]
./librabbitmq/amqp_private.h:233:12: note: expanded from macro 'DECLARE_CODEC_BASE_TYPE'
    return ntohx(val);                                                        \
           ^
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:32: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                               ^
/usr/include/libkern/_OSByteOrder.h:56:37: note: expanded from macro '__DARWIN_OSSwapConstInt64'
                (((__uint64_t)(x) & 0x0000ff0000000000ULL) >> 24) | \
````

I see two possible solutions:
1) suppress warnings related to long long (-Wno-long-long)
2) switch to -std=gnu99

I would prefer option 2, but as fas as I know, msvc doesn't support it.

### PR DESCRIPTION
**Pull request by skaes**
this eliminates lot's of warnings when compiling using clang on OS X and fixes #291.

### CODE REVIEW

**Comment by alanxz** [comment]
Not sure why circleCI got reenabled, you can safely ignore that failure. Also it appears as though travis-CI has re-opened Multi-OS CI, assuming I can get them to enable it for rabbitmq-c, there will be CI coverage for MacOSX as well as Linux and MSVC.

At this point I'd rather not switch rabbitmq-c entirely to `-std=gnu99`. The reason being is that rabbitmq-c needs to continue to support MSVC, which does not have proper C99 support, setting the project to be C99 systems with Clang, makes it easier for C99-isms to get added to rabbitmq-c, breaking builds on Win32.  A longer discussion about this can be found [here](https://github.com/alanxz/rabbitmq-c/pull/267#issuecomment-102263807).

That said: I'd also like to see rabbitmq-c compile warning-clean where reasonable so that warnings aren't ignored when they are emitted; and the state on MacOS X right now isn't good.

Doing a bit of twiddling, possibilities I've come across thus far:
- Add `-Wno-long-long` to the compile flags.
- Drop `-pedantic` from the compile flags.

**Comment by skaes** [comment]
I would go with dropping the `-pedantic`option.

**Comment by alanxz** [comment]
Agreed.

This was fixed in db335c6.

**Comment by skaes** [comment]
thx a lot.

**Pull request closed without merging**
