### PR TITLE
CMake: skip getaddrinfo detection on iOS.

### PR DESCRIPTION
**Pull request by alanxz**
getaddrinfo detection fails in CMake when trying to compile for iOS for some reason. Skip trying to detect it as its known to be there.

### CODE REVIEW

**Comment by alanxz** [comment]
I'm holding off adding iOS-specific code to the repo until I can get some kind of continuous integration setup for iOS, otherwise this will be broken fairly quickly I think.

**Comment by alanxz** [comment]
This is obsolete, rabbitmq-c can be built for iOS without modifying the CMakeLists.txt script.

**Comment by tagadapps** [comment]
Hello, I have tried to build rabbitmq-c as per your instructions
mkdir build && cd build
cmake ..
cmake --build . --config Release
However, when I link the lib in my project, XCode complains that the lib generated is for MacOS, not iOS. Do you know what I am missing ? Thanks in advance.

**Comment by pankkor** [comment]
@alanxz, I would appreciate any tip how to properly build for iOS using latest ios sdk and ssl support I'm interested in both simulator and arm architectures

**Pull request closed without merging**
