### PR TITLE
Added support for OpenVMS 8.3 (IA64 and Alpha)

### PR DESCRIPTION
**Pull request by coderReview**
If there is interest in having a port for OpenVMS please consider this pull request. Otherwise just close it. There is no impact on compilation for other OSs (used defined blocks).

- HP C V7.1 and 7.2 (tested)
- OpenVMS 8.3 and 8.4 (tested)

Thank you.

---
This change is [Reviewable](https://reviewable.io/reviews/alanxz/rabbitmq-c/446)

### CODE REVIEW

**Comment by alanxz** [comment]
I will consider support for OpenVMS provided some form of continuous integration that can be setup to regularly build rabbitmq-c on OpenVMS.

At one point in the past rabbitmq-c did support OpenVMS. I ended up removing this code (0b93d2604cd7db2517a6caa30eaeb6b8fe9ac2f5) for a couple reasons: 1) the library had changed significantly, and I had no idea whether it compiled, or if it did manage to compile whether it functioned correctly 2) having `#ifdef _OPENVMS` blocks sprinkled through the code adds a bit of complexity when reading the code.

If I were to take this on again, I'd like to make sure that any ports are known to work at whatever revision is available.

**Comment by coderReview** [comment]
If you have any suggestion on how to make it more readable just let me know. I manage to compile and run the code in 2 environments:

1- IA64, OpenVMS 8.4 - HP C v7.2
2- ALPHA, OpenVMS 8.3 - HP C v7.1

Thanks

**Comment by alanxz** [comment]
I understand that this code does work on OpenVMS today, but I'd like to make sure that this code continues to work in the future as rabbitmq-c evolves.

In order for me to accept this PR, I need to be able to build and run rabbitmq-c tests on OpenVMS on a regular basis as changes are added to rabbitmq-c (e.g., what is currently done with travis-ci.)

If you can figure out how to accomplish the above, I will work with you to get this merged.

**Comment by alanxz** [comment]
Closing as this is quite old and there's no progress towards any sort of continuous integration for it.

**Pull request closed without merging**
