### PR TITLE
Add methods to set timeout on AMQP RPCs

### PR DESCRIPTION
**Pull request by alanxz**
Add a method to set the timeout on AMQP RPCs sent from the client.

#403

---
This change is [Reviewable](https://reviewable.io/reviews/alanxz/rabbitmq-c/404)

### CODE REVIEW

**Comment by zbentley** [comment]
This looks great, thanks! I'll test it today or Friday EST.

Is it better to unconditionally force the socket closed on a timed-out RPC, or clearly inform the user that the connection is now in an indeterminate, almost-certainly-unusable state? I have seen RabbitMQ fail to "notice" that connections (without heartbeats) were closed for awhile, but only when they were closed via a hard `close` system call without disconnect negotiation. Would it make sense to send a hopeful disconnect RPC (without waiting for a reply) before closing the socket? 

I am out of my depth here, and may very well be totally wrong, though. What are your thoughts?

**Comment by alanxz** [comment]
This change will cause the underlying socket to be closed forcefully in the event of a timeout.

**Comment by zbentley** [comment]
I am able to induce RPC timeouts using this patch and a severely under-powered RabbitMQ instance. Thanks so much!

**Comment by minusdavid** [comment]
This looks great. I'm using this library via Net::AMQP::RabbitMQ, so I'm hoping that library can make use of this feature. I think it's exactly what I'm looking for to ensure a minimum of disruption to my message publisher.

**Pull request merged**
