### PR TITLE
Support openssl engine setting

### PR DESCRIPTION
**Pull request by maixuanhan**
Add 2 new APIs to support using openssl engine

```
amqp_set_ssl_engine : set openssl engine name
amqp_ssl_socket_set_key_engine : use this if the engine supports auto fetching key
```

---
This change is [Reviewable](https://reviewable.io/reviews/alanxz/rabbitmq-c/556)

### CODE REVIEW

**Comment by maixuanhan** [comment]
Hi, this is crucial for hardware-based encryption supported. Please help to point out why the Travis failed. Thanks.

**Comment by alanxz** [comment]
You need to add a string here: https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/amqp_api.c#L117 to match the new status being added.

**Comment by maixuanhan** [comment]
Now Travis is passed and AppVeyor is failed. I have no idea @@

**Comment by alanxz** [comment]
Looks like appveyor flaked when trying to download OpenSSL. I've re-triggered the build, hopefully that helps.

**Comment by alanxz** [comment]
Rebased and merged.  Sorry for the delay.

**Pull request closed without merging**
