### PR TITLE
Add Crypt32.lib for static OpenSSL 1.0.2 build support for Windows

### PR DESCRIPTION
**Pull request by ishmakov**
This change is [Reviewable](https://reviewable.io/reviews/alanxz/rabbitmq-c/368)

### CODE REVIEW

**Comment by alanxz** [comment]
Its odd to me that the FindOpenSSL.cmake doesn't reference the correct link-libraries. What version of CMake and what version of OpenSSL are you finding that this doesn't work?

**Comment by alanxz** [comment]
Crypt32.lib appears to be a windows link library and not an OpenSSL thing. Why does it need to be added here?

**Comment by ishmakov** [comment]
When i get project and try to build static with static OpenSSL 1.0.2. it's require Crypt32.lib

**Comment by alanxz** [comment]
For the same reasons described in #367, this isn't the correct way to fix this.

**Pull request closed without merging**
