### PR TITLE
Add EXTERNAL SASL mechanism.

### PR DESCRIPTION
**Pull request by alanxz**
Add support for the EXTERNAL SASL mechanism.

### CODE REVIEW

**Comment by alanxz** [comment]
Continuing this discussion from alanxz/SimpleAmqpClient#95

> I don't believe I am calling login twice. The diff shows '-' for the modified line.
> This is the example listener which I am trying to validate. Where is the broker involved?

Sorry, the diff marker don't come through on the e-mail.

The client authenticates against the broker (during `amqp_login()`), the broker must advertise that it supports the EXTERNAL SASL method before the client can attempt to use it. Usually this requires some configuration on the broker side before it'll work.

**Comment by dnj12345** [comment]
Hi Alan,
I was able to test the changes in this PR by modifying amqp_sendstring and amqps_sendstring examples and running them against a server supporting external auth. It seems to work.
How do we go about merging this stuff in? Thanks.

**Comment by alanxz** [comment]
I need to add some unit tests (especially for the string parsing bit), then it can be merged.

**Comment by dnj12345** [comment]
alan, I have a patch that adds unit tests and a couple of minor modifications to your changes. I tried to push them against this PR. However, I am getting a permission denied error. Do I need some sort of permission to push these commits to the external_sasl branch?

```
remote: Permission to alanxz/rabbitmq-c.git denied to dnj12345.
fatal: unable to access 'https://github.com/alanxz/rabbitmq-c.git/':
```

**Comment by alanxz** [comment]
You'll need to fork this repository on github, then do a push to your own repo.  At that point you can either open a new PR here, or reference the branch and I can pull those commits into this PR (both methods will retain your authorship on the commits).

**Comment by dnj12345** [comment]
Alan, my branch is https://github.com/dnj12345/rabbitmq-c/tree/external_sasl
I one fixup and one commit.

**Comment by alanxz** [comment]
One minor nit (left a comment - move the declaration to amqp_private.h as we don't really want to export this method from the library), otherwise looks good.

**Comment by dnj12345** [comment]
I move the declaration to amqp_private.h as u requested.
I noticed one strange thing I don't quite understand. 
Unless, I prefix the declaration with AMQP_PUBLIC_FUNCTION as shown below:

```
AMQP_PUBLIC_FUNCTION
int
sasl_mechanism_in_list(amqp_bytes_t mechanisms, amqp_sasl_method_enum method);
```

the symbol for  sasl_mechanism_in_list doesn't make it into the .so (verified this with
nm). When the symbol doesn't make it to the .so, the linker fails for the test 
test_sasl_mechansim. Since we need access to that function only for the tests,
I don't see why we need to declare it as a public function.
Any ideas?

**Comment by alanxz** [comment]
`AMQP_PUBLIC_FUNCTION` controls symbol visibility (the symbol is linked into the .so file, its just not exported so that it can be accessed externally, nor do we want this).  The workaround is to make sure the test links against a statically linked library instead of the shared library.  

I've gone ahead and fixed that in the build system, and tweaked your commits to make them work.

**Comment by alanxz** [comment]
This has been merged.  Thanks for the contribution!

**Comment by dnj12345** [comment]
cool! thanks.

**Pull request closed without merging**
